/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.courses;

import app.AppConfig;
import app.SessionManager;
import exception.ExistException;
import model.Course;
import model.User;
import ui.components.CustomDialog;
import ui.dashboard.HomePage;
import ui.lessons.Section;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author DELL
 */
public class CourseSingle extends javax.swing.JPanel {

    private Course currentCourse;
    private HomePage parentFrame;

    /**
     * Creates new form CourseSingle
     */
    public CourseSingle() {
        initComponents();
        setupComponents();
    }

    public void setParentFrame(HomePage frame) {
        this.parentFrame = frame;
    }

    private void setupComponents() {
        txtDescription.setLineWrap(true);
        txtDescription.setWrapStyleWord(true);
        txtDescription.setEditable(false);

        // ===== FIX TIÊU ĐỀ =====
        if (jPanel1 != null) {
            jPanel1.setVisible(true);
            jPanel1.setPreferredSize(new java.awt.Dimension(1200, 80));
            jPanel1.setMinimumSize(new java.awt.Dimension(800, 70));
        }

        if (jLabel1 != null) {
            jLabel1.setForeground(java.awt.Color.WHITE);
            jLabel1.setVisible(true);
            jLabel1.setText("Test Title"); // Test xem có hiện không
        }
        // =======================

        // Giới hạn kích thước tổng thể
        setPreferredSize(new java.awt.Dimension(1200, 900));
        setMaximumSize(new java.awt.Dimension(1200, 1000));
    }

    public void loadCourseData(Course course) {
        if (course == null) {
            return;
        }

        this.currentCourse = course;

        // Cập nhật tiêu đề
        jLabel1.setText(course.getTitle());

        // Cập nhật giá
        lbGia.setText(course.getPrice() == 0 ? "Free" : course.getPrice() + " VND");

        // Cập nhật mô tả
        txtDescription.setText(course.getDescription());

        // Load hình ảnh
        loadCourseImage(course.getCourseId());

        // Load các section (phần học)
        loadCourseSections(course);
    }

    private void loadCourseImage(int courseId) {
        String imagePath = CourseData.getImagePath(courseId);
        imagePath = imagePath.replace("/images610x360/", "/images/");
        try {
            ImageIcon icon = new ImageIcon(getClass().getResource(imagePath));
            if (icon.getIconWidth() > 0) {
                txtPicture.setIcon(icon);
            }
        } catch (Exception e) {
            System.err.println("Không thể load hình: " + imagePath);
        }
    }

    private void loadCourseSections(Course course) {
        // Xóa các section cũ
        mainPanel.removeAll();

        // Tạo sections mẫu dựa vào content
        List<String> sections = parseSectionsFromContent(course.getContent());
        //CustomDialog.getInstance().showSuccess(course.getContent(), "10239");

        for (int i = 0; i < sections.size(); i++) {
            String sectionTitle = "Phần " + (i + 1) + ": " + sections.get(i);
            Section section = new Section(
                    sectionTitle,
                    "3 Lessons",
                    "30 Mins",
                    List.of("Bài học 1", "Bài học 2", "Bài học 3")
            );
            mainPanel.add(section);
        }

        mainPanel.revalidate();
        mainPanel.repaint();
    }

    //"Nội dung chi tiết khóa học Java:\n\n" +
    //            "1. Cú pháp Java cơ bản\n" +
    //            "2. OOP trong Java\n" +
    //            "3. Collections Framework\n" +
    //            "4. Exception Handling\n" +
    //            "5. File I/O và Stream"
    private List<String> parseSectionsFromContent(String content) {
        List<String> sections = new ArrayList<>();
        if (content == null) {
            return sections;
        }

        String[] lines = content.split("\n");
        for (String line : lines) {
            line = line.trim();
            if (line.matches("^\\d+\\..*")) {
                sections.add(line.substring(line.indexOf(".") + 1).trim());
            }
        }

        return sections;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        lbGia = new javax.swing.JLabel();
        btStartNow = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        btQuayLai = new javax.swing.JButton();
        txtPicture = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lập trình  C++ cơ bản");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        lbGia.setBackground(new java.awt.Color(255, 255, 255));
        lbGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbGia.setForeground(new java.awt.Color(0, 0, 0));
        lbGia.setText("Free");

        btStartNow.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btStartNow.setContentAreaFilled(false);
        btStartNow.setOpaque(true);
        btStartNow.setBackground(Color.WHITE);
        btStartNow.setForeground(new java.awt.Color(255, 0, 51));
        btStartNow.setText("Start now");
        btStartNow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btStartNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStartNowActionPerformed(evt);
            }
        });

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        txtDescription.setText("This C++ course covers the fundamentals of \nprogramming, including syntax, data types, \ncontrol structures, functions, arrays, and basic \nobject-oriented programming. It provides\n practical coding exercises to help learners build \na strong foundation in C++.");
        jScrollPane1.setViewportView(txtDescription);

        btQuayLai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btQuayLai.setContentAreaFilled(false);
        btQuayLai.setOpaque(true);
        btQuayLai.setBackground(Color.WHITE);
        btQuayLai.setForeground(new java.awt.Color(0, 0, 0));
        btQuayLai.setText("Quay lại");
        btQuayLai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuayLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
                jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(lbGia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btStartNow))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(btQuayLai)))
                                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
                jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbGia)
                                        .addComponent(btStartNow))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btQuayLai)
                                .addContainerGap(13, Short.MAX_VALUE))
        );

        txtPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Lập trình C#.png"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel9Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel9Layout.createSequentialGroup()
                                                .addComponent(txtPicture)
                                                .addGap(0, 6, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtPicture)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel9, java.awt.BorderLayout.LINE_END);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Overview Course");

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new javax.swing.BoxLayout(mainPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane2.setViewportView(mainPanel);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel10Layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(0, 730, Short.MAX_VALUE))
                                        .addComponent(jScrollPane2))
                                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel10, java.awt.BorderLayout.CENTER);

        add(jPanel8, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btStartNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStartNowActionPerformed
        // TODO add your handling code here:
        User currenrUser = SessionManager.getInstance().getCurrentUser();
        if (currenrUser == null) {
            CustomDialog.getInstance().showError("Vui lòng đăng nhập để tiếp tục.", "Thông báo");
        } else {
            if (currentCourse.getPrice() == 0) {
                try {
                    boolean success = AppConfig.getEnrollmentService().enrollCourse(currenrUser.getUserId(), currentCourse.getCourseId());
                    if (success) {
                        CustomDialog.getInstance().showSuccess("Bạn đã đăng ký khóa học thành công!", "Thông báo");
                        CourseData.reloadUserCourses();
                    } else {
                        CustomDialog.getInstance().showError("Đăng ký khoá học thất bại!\nVui lòng liên hệ admin để được hỗ trợ.", "Error Message");
                    }
                } catch (ExistException e) {
                    CustomDialog.getInstance().showError(e.getMessage(), "Error Message");
                }
            } else {
                CustomDialog.getInstance().showError("Khóa học này có phí.\nChức năng thanh toán sẽ được cập nhật trong thời gian tới.", "Thông báo");
            }
        }


    }//GEN-LAST:event_btStartNowActionPerformed

    private void btQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuayLaiActionPerformed
        if (parentFrame != null) {
            BodyCourses courses = new BodyCourses();
            courses.setParentFrame(parentFrame);
            parentFrame.getBodyScrollPane().setViewportView(
                    parentFrame.wrapPanelCenter(courses)
            );
            parentFrame.getBodyScrollPane().revalidate();
            parentFrame.getBodyScrollPane().repaint();
        }
    }//GEN-LAST:event_btQuayLaiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btQuayLai;
    private javax.swing.JButton btStartNow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbGia;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JLabel txtPicture;
    // End of variables declaration//GEN-END:variables
}
