/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.lessons;

import javax.swing.JLabel;

/**
 *
 * @author DELL
 */
public class Section extends javax.swing.JPanel {

    private boolean expanded = false;

    /**
     * Creates new form NewJPanel
     *
     * @param title
     * @param info
     * @param time
     * @param lessons
     */
    public Section(String title, String info, String time, java.util.List<String> lessons) {
        initComponents();

        setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 50));

        jPanel3.setPreferredSize(new java.awt.Dimension(350, 50)); // Điều chỉnh width phù hợp

        // 🟢 Gán tiêu đề và thông tin
        lblTitle.setText("<html><div style='width: 320px;'>" + title + "</div></html>");
        lblInfo.setText(info);
        lblTime.setText(time);

        java.awt.EventQueue.invokeLater(() -> {
            int headerHeight = headerPanel.getPreferredSize().height;
            setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, Math.max(headerHeight + 5, 60)));
        });

        // 🟢 Ẩn phần nội dung ban đầu
        contentPanel.setVisible(false);

        // 🟢 Thêm các label bài học con vào contentPanel
        for (String lesson : lessons) {
            JLabel lbl = new JLabel("• " + lesson);
            lbl.setFont(new java.awt.Font("Segoe UI", 0, 14));
            lbl.setForeground(new java.awt.Color(60, 60, 60));
            lbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 20, 2, 5));
            contentPanel.add(lbl);
        }

        // 🟢 Xử lý nút xổ/thu
        btnToggle.addActionListener(e -> toggleContent());

        // 🟢 Nếu muốn click cả header để xổ/thu
        headerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toggleContent();
            }
        });

    }

    private void toggleContent() {
        expanded = !expanded;
        contentPanel.setVisible(expanded);

        // Đổi icon hoặc mũi tên
        if (expanded) {
            btnToggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/len.png")));

            // ✅ Tính toán chiều cao thực tế cần thiết
            int headerHeight = headerPanel.getPreferredSize().height;
            int contentHeight = contentPanel.getPreferredSize().height;
            int totalHeight = headerHeight + contentHeight + 10; // +10 để có chút padding

            setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, totalHeight));
        } else {
            btnToggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/xuong.png")));
            setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 50)); // 50px cho header
        }

        // Cập nhật lại bố cục hiển thị
        revalidate();
        repaint();

        if (getParent() != null) {
            getParent().revalidate();
            getParent().repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnToggle = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblTime = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel(); 
        contentPanel.setVisible(false);

        setLayout(new java.awt.BorderLayout());

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));
        headerPanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        btnToggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/xuong.png"))); // NOI18N
        btnToggle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnToggle, new java.awt.GridBagConstraints());

        headerPanel.add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblTime.setBackground(new java.awt.Color(255, 255, 255));
        lblTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTime.setForeground(new java.awt.Color(0, 0, 0));
        lblTime.setText("45 Mins");

        lblInfo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblInfo.setForeground(new java.awt.Color(0, 0, 0));
        lblInfo.setText("4 Lession");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTime)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTime)
                    .addComponent(lblInfo))
                .addContainerGap())
        );

        headerPanel.add(jPanel2, java.awt.BorderLayout.LINE_END);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 0));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Phần 1: Code C++");
        lblTitle.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(lblTitle);

        headerPanel.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(headerPanel, java.awt.BorderLayout.PAGE_START);

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setLayout(new javax.swing.BoxLayout(contentPanel, javax.swing.BoxLayout.Y_AXIS));
        add(contentPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnToggle;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
