/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.exercises;

import model.CodingQuestion;
import model.Course;
import ui.dashboard.HomePage;
import ui.submission.SubmissionPage;

import java.awt.*;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;

/**
 *
 * @author DELL
 */
public class ExerciseDetail extends javax.swing.JPanel {

    private Exercises currentExercise;
    private CodingQuestion currentCodingQuestion;
    private HomePage parentFrame;
    private Course currentCourse;

    /**
     * Creates a new form ExerciseDetail
     */
    public ExerciseDetail() {
        initComponents();

        txtDescription.setEditable(false);
        txtDauVao.setEditable(false);
        txtGioiHan.setEditable(false);
        txtDauRa.setEditable(false);
        txtInput1.setEditable(false);
        txtOutput.setEditable(false);

    }


    public void setParentFrame(HomePage frame) {
        this.parentFrame = frame;
    }

    public void setCurrentCourse(Course currentCourse) {
        this.currentCourse = currentCourse;
    }

    public void setExerciseData(CodingQuestion codingQuestion) {
        this.currentCodingQuestion = codingQuestion;

        // Hiển thị thông tin bài tập
        txtTitle.setText(codingQuestion.getTitle());
        txtDescription.setText(codingQuestion.getDescription());
        txtDauVao.setText(codingQuestion.getInputFormat());
        txtGioiHan.setText(codingQuestion.getConstraints());
        txtDauRa.setText(codingQuestion.getOutputFormat());
        txtInput1.setText(codingQuestion.getSampleInput());
        txtOutput.setText(codingQuestion.getSampleOutput());

        // Cuộn về đầu các text area
        txtDescription.setCaretPosition(0);
        txtDauVao.setCaretPosition(0);
        txtGioiHan.setCaretPosition(0);
        txtDauRa.setCaretPosition(0);
        txtInput1.setCaretPosition(0);
        txtOutput.setCaretPosition(0);
    }

    public void setExerciseData(Exercises exercise) {
        this.currentExercise = exercise;

        // Hiển thị thông tin bài tập
        txtTitle.setText(exercise.getBai());
        txtDescription.setText(exercise.getMoTa());
        txtDauVao.setText(exercise.getDauVao());
        txtGioiHan.setText(exercise.getGioiHan());
        txtDauRa.setText(exercise.getDauRa());
        txtInput1.setText(exercise.getInput());
        txtOutput.setText(exercise.getOutput());

        // Cuộn về đầu các text area
        txtDescription.setCaretPosition(0);
        txtDauVao.setCaretPosition(0);
        txtGioiHan.setCaretPosition(0);
        txtDauRa.setCaretPosition(0);
        txtInput1.setCaretPosition(0);
        txtOutput.setCaretPosition(0);
    }

    private void copyToClipboard(String text) {
        StringSelection selection = new StringSelection(text);
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(selection, null);
    }

    private void openSubmissionPage() {
        if (currentCodingQuestion != null && parentFrame != null) {
            SubmissionPage submissionPage = new SubmissionPage();
            submissionPage.setExerciseData(currentCodingQuestion);
            submissionPage.setParentFrame(parentFrame);

            submissionPage.setCurrentCourse(currentCourse);

            parentFrame.getBodyScrollPane().setViewportView(parentFrame.wrapPanelCenter(submissionPage));
            parentFrame.getBodyScrollPane().revalidate();
            parentFrame.getBodyScrollPane().repaint();
        }
    }

    private void goBackToCodingExercises() {
        if (parentFrame != null) {
            BodyCodingExercises codingPanel = new BodyCodingExercises();
            codingPanel.setParentFrame(parentFrame);

            // THÊM DÒNG NÀY: Load lại dữ liệu test khi quay về
            if (currentCourse != null) {
                TestDataExample.addSampleData(codingPanel);
                codingPanel.callBackForLoadTable(currentCourse);
            } else {
                TestDataExample.addSampleData(codingPanel);
            }

            parentFrame.getBodyScrollPane().setViewportView(parentFrame.wrapPanelCenter(codingPanel));
            parentFrame.getBodyScrollPane().revalidate();
            parentFrame.getBodyScrollPane().repaint();
        }

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDauVao = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtGioiHan = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtDauRa = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtInput1 = new javax.swing.JTextArea();
        btCopyOutput = new javax.swing.JButton();
        btCopyInput = new javax.swing.JButton();
        btQuayLai = new javax.swing.JButton();
        btGuiBaiGiai = new javax.swing.JButton();
        txtTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDescription.setColumns(20);
        txtDescription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDescription.setForeground(new java.awt.Color(0, 0, 0));
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 890, 150));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ví dụ: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        txtOutput.setColumns(20);
        txtOutput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtOutput.setForeground(new java.awt.Color(0, 0, 0));
        txtOutput.setRows(5);
        jScrollPane2.setViewportView(txtOutput);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 790, 50));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Đầu vào");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        txtDauVao.setColumns(20);
        txtDauVao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDauVao.setForeground(new java.awt.Color(0, 0, 0));
        txtDauVao.setRows(5);
        jScrollPane3.setViewportView(txtDauVao);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 890, 50));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Giới hạn");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        txtGioiHan.setColumns(20);
        txtGioiHan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtGioiHan.setForeground(new java.awt.Color(0, 0, 0));
        txtGioiHan.setRows(5);
        jScrollPane4.setViewportView(txtGioiHan);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 890, 50));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Output");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Đầu ra");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        txtDauRa.setColumns(20);
        txtDauRa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDauRa.setForeground(new java.awt.Color(0, 0, 0));
        txtDauRa.setRows(5);
        jScrollPane5.setViewportView(txtDauRa);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 890, 50));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Input");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        txtInput1.setColumns(20);
        txtInput1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtInput1.setForeground(new java.awt.Color(0, 0, 0));
        txtInput1.setRows(5);
        jScrollPane6.setViewportView(txtInput1);

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 790, 50));

        btCopyOutput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btCopyOutput.setContentAreaFilled(false);
        btCopyOutput.setOpaque(true);
        btCopyOutput.setBackground(Color.WHITE);
        btCopyOutput.setForeground(new java.awt.Color(0, 0, 0));
        btCopyOutput.setText("Copy");
        btCopyOutput.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCopyOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCopyOutputActionPerformed(evt);
            }
        });
        jPanel1.add(btCopyOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 550, -1, -1));

        btCopyInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btCopyInput.setContentAreaFilled(false);
        btCopyInput.setOpaque(true);
        btCopyInput.setBackground(Color.WHITE);
        btCopyInput.setForeground(new java.awt.Color(0, 0, 0));
        btCopyInput.setText("Copy");
        btCopyInput.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCopyInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCopyInputActionPerformed(evt);
            }
        });
        jPanel1.add(btCopyInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 470, -1, -1));

        btQuayLai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btQuayLai.setContentAreaFilled(false);
        btQuayLai.setOpaque(true);
        btQuayLai.setBackground(Color.WHITE);
        btQuayLai.setForeground(new java.awt.Color(0, 0, 0));
        btQuayLai.setText("Quay lại");
        btQuayLai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuayLaiActionPerformed(evt);
            }
        });

        btGuiBaiGiai.setBackground(new java.awt.Color(255, 153, 102));
        btGuiBaiGiai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btGuiBaiGiai.setForeground(new java.awt.Color(0, 0, 0));
        btGuiBaiGiai.setText("Gửi bài giải");
        btGuiBaiGiai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btGuiBaiGiai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuiBaiGiaiActionPerformed(evt);
            }
        });

        txtTitle.setBackground(new java.awt.Color(255, 255, 255));
        txtTitle.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(40, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 912, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btGuiBaiGiai, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 1174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(btGuiBaiGiai)
                                .addGap(46, 46, 46)
                                .addComponent(btQuayLai)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(67, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(675, Short.MAX_VALUE)))
        );

        add(jPanel2, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void btGuiBaiGiaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuiBaiGiaiActionPerformed
        openSubmissionPage();
    }//GEN-LAST:event_btGuiBaiGiaiActionPerformed

    private void btQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuayLaiActionPerformed
        goBackToCodingExercises();
    }//GEN-LAST:event_btQuayLaiActionPerformed

    private void btCopyInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCopyInputActionPerformed
        copyToClipboard(txtInput1.getText());
    }//GEN-LAST:event_btCopyInputActionPerformed

    private void btCopyOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCopyOutputActionPerformed
        copyToClipboard(txtOutput.getText());
    }//GEN-LAST:event_btCopyOutputActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCopyInput;
    private javax.swing.JButton btCopyOutput;
    private javax.swing.JButton btGuiBaiGiai;
    private javax.swing.JButton btQuayLai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea txtDauRa;
    private javax.swing.JTextArea txtDauVao;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextArea txtGioiHan;
    private javax.swing.JTextArea txtInput1;
    private javax.swing.JTextArea txtOutput;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
