/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.auth;

import app.AppConfig;
import app.SessionManager;
import exception.ValidationException;
import model.User;
import ui.components.CustomDialog;
import ui.components.CustomKey;
import ui.dashboard.HomePage;

import java.awt.*;

/**
 *
 * @author DELL
 */
public class Login extends javax.swing.JPanel {

    private boolean isPasswordVisible = false;
    private HomePage parentFrame;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        txtKey.setEchoChar('•');
        txtTK.setForeground(Color.GRAY);
        txtKey.setForeground(Color.GRAY);
        CustomKey.getInstance().bindEnterKeyToContainer(this, btLogin);
    }

    public void setParentFrame(HomePage frame) {
        this.parentFrame = frame;
    }

    private void clearFields() {
        txtTK.setText("");
        txtKey.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTK = new javax.swing.JTextField("Username or Email*")
        ;
        jLabel3 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        btLogin = new javax.swing.JButton();
        btRegister = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtKey = new javax.swing.JPasswordField("Password*")
        ;
        btAnHien = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.lightGray));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/pixelcut-export.png"))); // NOI18N
        jLabel1.setText("VNPTedu Login");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/OIP (6) (1).jpg"))); // NOI18N

        txtTK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTK.setForeground(new java.awt.Color(0, 0, 0));
        txtTK.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTK.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTKFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTKFocusLost(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/key.jpg"))); // NOI18N

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox1.setText("Remember me");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        btLogin.setBackground(new java.awt.Color(255, 153, 102));
        btLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btLogin.setForeground(new java.awt.Color(255, 255, 255));
        btLogin.setText("Login");
        btLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });

        btRegister.setBackground(new java.awt.Color(255, 153, 102));
        btRegister.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btRegister.setForeground(new java.awt.Color(255, 255, 255));
        btRegister.setText("Register");
        btRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegisterActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Lost your password?");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        txtKey.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtKey.setForeground(new java.awt.Color(0, 0, 0));
        txtKey.setBorder(null);
        txtKey.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtKeyFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                txtKeyFocusLost(evt);
            }
        });

        btAnHien.setBackground(new java.awt.Color(204, 204, 204));
        btAnHien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/an.jpg"))); // NOI18N
        btAnHien.setBorder(null);
        btAnHien.setBorderPainted(false);
        btAnHien.setContentAreaFilled(false);
        btAnHien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAnHien.setFocusPainted(false);
        btAnHien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnHienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtKey)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btAnHien)
                                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btAnHien, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtKey, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("I don't have an account! ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btRegister))
                                        .addComponent(jLabel4)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel1)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel2)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtTK, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel3)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addComponent(btLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTK))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 3, Short.MAX_VALUE)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox1)
                                .addGap(17, 17, 17)
                                .addComponent(btLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(btRegister))
                                .addGap(20, 20, 20))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(85, 352, 98, 353);
        add(jPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed

        String usernameOrEmail = txtTK.getText().trim();
        String password = new String(txtKey.getPassword());

        if (usernameOrEmail.isEmpty() || password.isEmpty()) {
            CustomDialog.getInstance().showWarning("Vui lòng nhập đầy đủ thông tin!", "Thông báo");
            return;
        }

        try {
            User user = AppConfig.getUserService().login(usernameOrEmail, password);
            //CustomDialog.getInstance().showSuccess(user.toString());
            if (user != null) {
                SessionManager.getInstance().login(user);
                CustomDialog.getInstance().showSuccess("Welcome " + user.getFullName(), "Login Success");
                // handleSuccessfulLogin(user);
                if (parentFrame != null) {
                    parentFrame.updateLoginStatus();
                    // Chuyển về trang Home
                    parentFrame.navigateToHome();
                }

                selectRememberMe(usernameOrEmail);

                // Xóa dữ liệu nhập
                clearFields();
            } else {
                CustomDialog.getInstance().showError("Tên đăng nhập hoặc mật khẩu không đúng!", "Thông báo");
            }
        } catch (ValidationException e) {
            CustomDialog.getInstance().showError("Login failed: " + e.getMessage(), "Error Message");
        } catch (Exception e) {
            CustomDialog.getInstance().showError("An unexpected error occurred: " + e.getMessage(), "Error Message");
            System.err.println(e.getMessage());
        }


    }//GEN-LAST:event_btLoginActionPerformed

    private void btRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegisterActionPerformed
        if (parentFrame != null) {
            Register registerPanel = new Register();
            registerPanel.setParentFrame(parentFrame);
            parentFrame.getBodyScrollPane().setViewportView(parentFrame.wrapPanelCenter(registerPanel));
            parentFrame.getBodyScrollPane().revalidate();
            parentFrame.getBodyScrollPane().repaint();
        }
    }//GEN-LAST:event_btRegisterActionPerformed

    private void txtTKFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTKFocusGained
        if (txtTK.getText().equals("Username or Email*")) {
            txtTK.setText("");
            txtTK.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtTKFocusGained

    private void txtKeyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKeyFocusLost
        String password = new String(txtKey.getPassword()).trim();
        if (password.isEmpty()) {
            txtKey.setText("Password*");
            txtKey.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtKeyFocusLost

    private void txtTKFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTKFocusLost
        if (txtTK.getText().isEmpty()) {
            txtTK.setText("Username or Email*");
            txtTK.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtTKFocusLost

    private void txtKeyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKeyFocusGained
        String password = new String(txtKey.getPassword()).trim();
        if (password.equals("Password*")) {
            txtKey.setText("");
            txtKey.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtKeyFocusGained

    private void btAnHienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnHienActionPerformed
        if (isPasswordVisible) {
            // Ẩn mật khẩu
            txtKey.setEchoChar('•');
            btAnHien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/an.jpg")));
            isPasswordVisible = false;
        } else {
            // Hiện mật khẩu
            txtKey.setEchoChar((char) 0);
            btAnHien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/hiện.jpg")));
            isPasswordVisible = true;
        }
    }//GEN-LAST:event_btAnHienActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        if (parentFrame != null) {
            LostPassword lostPassword = new LostPassword();
            lostPassword.setParentFrame(parentFrame);
            parentFrame.getBodyScrollPane().setViewportView(parentFrame.wrapPanelCenter(lostPassword));
            parentFrame.getBodyScrollPane().revalidate();
            parentFrame.getBodyScrollPane().repaint();
        }
    }

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        jLabel4.setForeground(java.awt.Color.BLUE);
    }

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        jLabel4.setForeground(java.awt.Color.BLACK);
    }

    private void selectRememberMe(String usernameOrEmail) {
        // === START: Remember Me Logic ===
        java.util.prefs.Preferences prefs = java.util.prefs.Preferences.userNodeForPackage(Login.class);
        if (jCheckBox1.isSelected()) {
            // Save the username and the preference
            prefs.put("username", usernameOrEmail);
            prefs.putBoolean("rememberMe", true);
        } else {
            // Clear the preferences if the box is not checked
            prefs.remove("username");
            prefs.remove("rememberMe");
        }
        // === END: Remember Me Logic ===
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnHien;
    private javax.swing.JButton btLogin;
    private javax.swing.JButton btRegister;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txtKey;
    private javax.swing.JTextField txtTK;
    // End of variables declaration//GEN-END:variables
}
