/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.auth;

import app.AppConfig;
import exception.ValidationException;
import ui.components.CustomDialog;
import ui.components.CustomKey;
import ui.dashboard.HomePage;
import utils.Validator;

import java.awt.*;

/**
 *
 * @author DELL
 */
public class LostPassword extends javax.swing.JPanel {

    private HomePage parentFrame;
    private boolean isPasswordVisible1 = false;
    private boolean isPasswordVisible2 = false;

    /**
     * Creates new form LostPassword
     */
    public LostPassword() {
        initComponents();
        txtEmail.setForeground(Color.GRAY);
        txtOTP.setForeground(Color.GRAY);
        CustomKey.getInstance().bindEnterKeyToContainer(this, btGuiOTP);
    }

    public void setParentFrame(HomePage frame) {
        this.parentFrame = frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField("Email")
        ;
        btGuiOTP = new javax.swing.JButton();
        lbTB = new javax.swing.JLabel();
        txtOTP = new javax.swing.JTextField("OTP")
        ;
        jLabel12 = new javax.swing.JLabel();
        btXacNhan = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btAHNP1 = new javax.swing.JButton();
        txtPass1 = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        btCNP = new javax.swing.JButton();
        txtCNPass = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.lightGray));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/pixelcut-export.png"))); // NOI18N
        jLabel1.setText("Password reset OTP page");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/OIP (6) (1).jpg"))); // NOI18N

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("OTP");
        jLabel3.setToolTipText("");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(0, 0, 0));
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        btGuiOTP.setBackground(new java.awt.Color(255, 153, 102));
        btGuiOTP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btGuiOTP.setForeground(new java.awt.Color(0, 0, 0));
        btGuiOTP.setText("OTP");
        btGuiOTP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btGuiOTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuiOTPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btGuiOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btGuiOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lbTB.setBackground(new java.awt.Color(204, 204, 204));
        lbTB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbTB.setForeground(new java.awt.Color(0, 0, 0));
        lbTB.setToolTipText("");

        txtOTP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtOTP.setForeground(new java.awt.Color(0, 0, 0));
        txtOTP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtOTPFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                txtOTPFocusLost(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("New password");

        btXacNhan.setBackground(new java.awt.Color(255, 153, 102));
        btXacNhan.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btXacNhan.setForeground(new java.awt.Color(0, 0, 0));
        btXacNhan.setText("Xác nhận");
        btXacNhan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXacNhanActionPerformed(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Confirm new password");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btAHNP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/an.jpg"))); // NOI18N
        btAHNP1.setBorderPainted(false);
        btAHNP1.setContentAreaFilled(false);
        btAHNP1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAHNP1.setFocusPainted(false);
        btAHNP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAHNP1ActionPerformed(evt);
            }
        });

        txtPass1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPass1.setForeground(new java.awt.Color(0, 0, 0));
        txtPass1.setBorder(null);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap(430, Short.MAX_VALUE)
                                .addComponent(btAHNP1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(txtPass1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 45, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btAHNP1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPass1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btCNP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/an.jpg"))); // NOI18N
        btCNP.setBorderPainted(false);
        btCNP.setContentAreaFilled(false);
        btCNP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCNP.setFocusPainted(false);
        btCNP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCNPActionPerformed(evt);
            }
        });

        txtCNPass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCNPass.setForeground(new java.awt.Color(0, 0, 0));
        txtCNPass.setBorder(null);
        txtCNPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCNPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap(424, Short.MAX_VALUE)
                                .addComponent(btCNP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txtCNPass, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 47, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(btCNP, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 2, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCNPass, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel17)
                                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel12)
                                                .addComponent(jLabel1)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel2)
                                                                .addComponent(jLabel3))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(lbTB, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(36, 36, 36))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lbTB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(345, 345, 345)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        if (txtEmail.getText().equals("Email")) {
            txtEmail.setText("");
            txtEmail.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        if (txtEmail.getText().isEmpty()) {
            txtEmail.setText("Email");
            txtEmail.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btGuiOTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuiOTPActionPerformed
        String email = txtEmail.getText().trim();
        try {
            Validator.validateEmail(email);
            CustomDialog.getInstance().showSuccess("Đang gửi mã OTP...", "Thông báo");
            boolean success = AppConfig.getUserService().sendPasswordResetCode(email);
            if (success) {
                CustomDialog.getInstance().showSuccess("Đã gửi mã OTP", "Thông báo");
                btGuiOTP.setEnabled(false);
                CustomKey.getInstance().bindEnterKeyToContainer(this, btXacNhan);
            }
        } catch (ValidationException e) {
            CustomDialog.getInstance().showError(e.getMessage(), "Thông báo");
        } catch (Exception e) {
            CustomDialog.getInstance().showError("Lỗi trong việc gửi OTP: " + e.getMessage(), "Thông báo");
        }
    }//GEN-LAST:event_btGuiOTPActionPerformed

    private void txtOTPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOTPFocusGained
        if (txtOTP.getText().equals("OTP")) {
            txtOTP.setText("");
            txtOTP.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtOTPFocusGained

    private void txtOTPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOTPFocusLost
        if (txtOTP.getText().isEmpty()) {
            txtOTP.setText("OTP");
            txtOTP.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtOTPFocusLost

    private void btXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXacNhanActionPerformed
        String email = txtEmail.getText().trim();
        String code = txtOTP.getText().trim();
        String password = txtPass1.getText().trim();
        String confirmPassword = txtCNPass.getText().trim();
        if (password.equals(confirmPassword)) {
            try {
                boolean success = AppConfig.getUserService().resetPasswordWithCode(email, code, password);
                if (success) {
                    CustomDialog.getInstance().showSuccess("Đã đổi mật khẩu mới! Vui lòng đăng nhập lại", "Thông báo");
                    if (parentFrame != null) {
                        Login loginPanel = new Login();
                        loginPanel.setParentFrame(parentFrame);
                        parentFrame.getBodyScrollPane().setViewportView(parentFrame.wrapPanelCenter(loginPanel));
                        parentFrame.getBodyScrollPane().revalidate();
                        parentFrame.getBodyScrollPane().repaint();
                    }
                }
            } catch (ValidationException e) {
                CustomDialog.getInstance().showError(e.getMessage(), "Error Message");
            } catch (Exception e) {
                CustomDialog.getInstance().showError("Lỗi trong việc đặt lại mật khẩu: " + e.getMessage(), "Error Message");
            }
        } else {
            CustomDialog.getInstance().showError("Mật khẩu không khớp", "Thông báo");
        }
    }//GEN-LAST:event_btXacNhanActionPerformed

    private void btAHNP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAHNP1ActionPerformed
        if (isPasswordVisible1) {
            // Ẩn mật khẩu
            txtPass1.setEchoChar('•');
            btAHNP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/an.jpg")));
            isPasswordVisible1 = false;
        } else {
            // Hiện mật khẩu
            txtPass1.setEchoChar((char) 0);
            btAHNP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/hiện.jpg")));
            isPasswordVisible1 = true;
        }
    }//GEN-LAST:event_btAHNP1ActionPerformed

    private void btCNPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCNPActionPerformed
        if (isPasswordVisible2) {
            // Ẩn mật khẩu
            txtCNPass.setEchoChar('•');
            btCNP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/an.jpg")));
            isPasswordVisible2 = false;
        } else {
            // Hiện mật khẩu
            txtCNPass.setEchoChar((char) 0);
            btCNP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/hiện.jpg")));
            isPasswordVisible2 = true;
        }
    }//GEN-LAST:event_btCNPActionPerformed

    private void txtCNPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCNPassActionPerformed

    }//GEN-LAST:event_txtCNPassActionPerformed

    private void btKiemTraActionPerformed(java.awt.event.ActionEvent evt) {
        String email = txtEmail.getText().trim();
        String code = txtOTP.getText().trim();
        String password = txtPass1.getText().trim();
        String confirmPassword = txtCNPass.getText().trim();
        if (!password.equals(confirmPassword)) {
            try {
                boolean success = AppConfig.getUserService().resetPasswordWithCode(email, code, password);
                if (success) {
                    CustomDialog.getInstance().showSuccess("Đã đổi mật khẩu mới! Vui lòng đăng nhập lại", "Thông báo");
                    if (parentFrame != null) {
                        Login loginPanel = new Login();
                        loginPanel.setParentFrame(parentFrame);
                        parentFrame.getBodyScrollPane().setViewportView(parentFrame.wrapPanelCenter(loginPanel));
                        parentFrame.getBodyScrollPane().revalidate();
                        parentFrame.getBodyScrollPane().repaint();
                    }
                }
            } catch (ValidationException e) {
                CustomDialog.getInstance().showError(e.getMessage(), "Error Message");
            } catch (Exception e) {
                CustomDialog.getInstance().showError("Lỗi trong việc đặt lại mật khẩu: " + e.getMessage(), "Error Message");
            }
        }


    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAHNP1;
    private javax.swing.JButton btCNP;
    private javax.swing.JButton btGuiOTP;
    private javax.swing.JButton btXacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbTB;
    private javax.swing.JPasswordField txtCNPass;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtOTP;
    private javax.swing.JPasswordField txtPass1;
    // End of variables declaration//GEN-END:variables
}
